While {true} do {
	if (PlayerSide==west) then {
		mwp1 = CreateMarkerLocal ["mwp1", position w_p_1];
		mwp1 setMarkerShapeLocal "Icon";
		mwp1 setMarkerTypeLocal "b_unknown";
		mwp1 setMarkerTextLocal name w_p_1;
		mwp2 = CreateMarkerLocal ["mwp2", position w_p_2];
		mwp2 setMarkerShapeLocal "Icon"; 
		mwp2 setMarkerTypeLocal "b_unknown";
		mwp2 setMarkerTextLocal name w_p_2;
		mwp3 = CreateMarkerLocal ["mwp3", position w_p_3];
		mwp3 setMarkerShapeLocal "Icon"; 
		mwp3 setMarkerTypeLocal "b_unknown";
		mwp3 setMarkerTextLocal name w_p_3;
		mwp4 = CreateMarkerLocal ["mwp4", position w_p_4];
		mwp4 setMarkerShapeLocal "Icon"; 
		mwp4 setMarkerTypeLocal "b_unknown";
		mwp4 setMarkerTextLocal name w_p_4;
		mwp5 = CreateMarkerLocal ["mwp5", position w_p_5];
		mwp5 setMarkerShapeLocal "Icon"; 
		mwp5 setMarkerTypeLocal "b_unknown";
		mwp5 setMarkerTextLocal name w_p_5;
		mwp6 = CreateMarkerLocal ["mwp6", position w_p_6];
		mwp6 setMarkerShapeLocal "Icon"; 
		mwp6 setMarkerTypeLocal "b_unknown";
		mwp6 setMarkerTextLocal name w_p_6;
		mwp7 = CreateMarkerLocal ["mwp7", position w_p_7];
		mwp7 setMarkerShapeLocal "Icon"; 
		mwp7 setMarkerTypeLocal "b_unknown";
		mwp7 setMarkerTextLocal name w_p_7;
		mwp8 = CreateMarkerLocal ["mwp8", position w_p_8];
		mwp8 setMarkerShapeLocal "Icon"; 
		mwp8 setMarkerTypeLocal "b_unknown";
		mwp8 setMarkerTextLocal name w_p_8;
		mwp9 = CreateMarkerLocal ["mwp9", position w_p_9];
		mwp9 setMarkerShapeLocal "Icon"; 
		mwp9 setMarkerTypeLocal "b_unknown";
		mwp9 setMarkerTextLocal name w_p_9;
		sleep 5;
		DeleteMarkerLocal mwp1;
		DeleteMarkerLocal mwp2;
		DeleteMarkerLocal mwp3;
		DeleteMarkerLocal mwp4;
		DeleteMarkerLocal mwp5;
		DeleteMarkerLocal mwp6;
		DeleteMarkerLocal mwp7;
		DeleteMarkerLocal mwp8;
		DeleteMarkerLocal mwp9;
	};
	if (PlayerSide==east) then {
		ewp1 = CreateMarkerLocal ["ewp1", position e_p_1];
		ewp1 setMarkerShapeLocal "Icon";
		ewp1 setMarkerTypeLocal "o_unknown";
		ewp1 setMarkerTextLocal name e_p_1;
		ewp2 = CreateMarkerLocal ["ewp2", position e_p_2];
		ewp2 setMarkerShapeLocal "Icon";
		ewp2 setMarkerTypeLocal "o_unknown";
		ewp2 setMarkerTextLocal name e_p_2;
		ewp3 = CreateMarkerLocal ["ewp3", position e_p_3];
		ewp3 setMarkerShapeLocal "Icon";
		ewp3 setMarkerTypeLocal "o_unknown";
		ewp3 setMarkerTextLocal name e_p_3;
		ewp4 = CreateMarkerLocal ["ewp4", position e_p_4];
		ewp4 setMarkerShapeLocal "Icon";
		ewp4 setMarkerTypeLocal "o_unknown";
		ewp4 setMarkerTextLocal name e_p_4;
		ewp5 = CreateMarkerLocal ["ewp5", position e_p_5];
		ewp5 setMarkerShapeLocal "Icon";
		ewp5 setMarkerTypeLocal "o_unknown";
		ewp5 setMarkerTextLocal name e_p_5;
		ewp6 = CreateMarkerLocal ["ewp6", position e_p_6];
		ewp6 setMarkerShapeLocal "Icon";
		ewp6 setMarkerTypeLocal "o_unknown";
		ewp6 setMarkerTextLocal name e_p_6;
		ewp7 = CreateMarkerLocal ["ewp7", position e_p_7];
		ewp7 setMarkerShapeLocal "Icon";
		ewp7 setMarkerTypeLocal "o_unknown";
		ewp7 setMarkerTextLocal name e_p_7;
		ewp8 = CreateMarkerLocal ["ewp8", position e_p_8];
		ewp8 setMarkerShapeLocal "Icon";
		ewp8 setMarkerTypeLocal "o_unknown";
		ewp8 setMarkerTextLocal name e_p_8;
		ewp9 = CreateMarkerLocal ["ewp9", position e_p_9];
		ewp9 setMarkerShapeLocal "Icon";
		ewp9 setMarkerTypeLocal "o_unknown";
		ewp9 setMarkerTextLocal name e_p_9;
		sleep 5;
		DeleteMarkerLocal ewp1;
		DeleteMarkerLocal ewp2;
		DeleteMarkerLocal ewp3;
		DeleteMarkerLocal ewp4;
		DeleteMarkerLocal ewp5;
		DeleteMarkerLocal ewp6;
		DeleteMarkerLocal ewp7;
		DeleteMarkerLocal ewp8;
		DeleteMarkerLocal ewp9;
	};
};
